#!/usr/bin/with-contenv sh

if ! [ -f "/config/args.conf" ]; then
  echo "[default-configs] restoring default 'args.conf'."
  cp /config.default/args.conf /config/
fi

if ! [ -f "/config/artists.txt" ]; then
  echo "[default-configs] restoring default 'artists.txt'."
  cp /config.default/artists.txt /config/
fi

# always update the post-execution.sh script
echo "[default-configs] updating default 'post-execution.sh'."
cp -f /config.default/post-execution.sh /config/

# always update the genres_cache.txt
echo "[default-configs] updating default 'genres_cache.txt'."
cp -f /config.default/genres_cache.txt /config/

ln -fs /config/args.conf /etc/yt-dlp.conf

# check if youtubedl_quality is set, else assign default
youtubedl_quality="${youtubedl_quality:-best}"

# shellcheck disable=SC2016
sed -i -E 's!\$youtubedl_quality!'"${youtubedl_quality}"'!g' /config.default/format