#!/usr/bin/with-contenv bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /downloads
chown -R abc:abc /music
chown -R abc:abc /var/run/s6/services
chown -R abc:abc /root

chmod +x /app/yt-dlp/updater.sh
chmod +x /app/yt-dlp/yt-dlp.sh
chmod +x /config/post-execution.sh
chmod +x /app/extended-scripts/add_mp3_thumbnail.py
chmod +x /app/extended-scripts/artist_disambiguator.py
chmod +x /app/extended-scripts/artists_folder_capitalize.py
chmod +x /app/extended-scripts/artists_folders_fixer.py
chmod +x /app/extended-scripts/artists_folders_merger.py
chmod +x /app/extended-scripts/artists_invalid_characters_remover.py
chmod +x /app/extended-scripts/artists_tag_fixer.py
chmod +x /app/extended-scripts/capitalize_fixer.py
chmod +x /app/extended-scripts/capitalize_folders_and_tags_accents.py
chmod +x /app/extended-scripts/capitalize_tags_files_and_folders.py
chmod +x /app/extended-scripts/complete_missing_covers.sh
chmod +x /app/extended-scripts/downloads_invalid_characters_remover.py
chmod +x /app/extended-scripts/downloads_mover.py
chmod +x /app/extended-scripts/dz_db_downloader.py
chmod +x /app/extended-scripts/genre_fixer.py
chmod +x /app/extended-scripts/jellyfin_album_downloader.py
chmod +x /app/extended-scripts/jellyfin_artist_downloader.py
chmod +x /app/extended-scripts/lastgenre.py
chmod +x /app/extended-scripts/loudnorm.sh
chmod +x /app/extended-scripts/missing_covers_downloader.py
chmod +x /app/extended-scripts/music_invalid_characters_remover.py
chmod +x /app/extended-scripts/plex_album_downloader.py
chmod +x /app/extended-scripts/plex_artist_downloader.py
chmod +x /app/extended-scripts/release_year_update.py
chmod +x /app/extended-scripts/tags_and_folders_strings_fixer.py
chmod +x /app/extended-scripts/tracks_updater.py
chmod +x /app/extended-scripts/trash_collector.py
chmod +x /app/extended-scripts/unofficial_albums_mover.py
chmod +x /app/extended-scripts/untitled_album_cover.py
chmod +x /app/extended-scripts/untitled_album_folder.py
chmod +x /app/extended-scripts/untitled_album_tag.py
chmod +x /app/extended-scripts/various_artists_cover.py