#!/usr/bin/with-contenv bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /downloads
chown -R abc:abc /music
chown -R abc:abc /var/run/s6/services
chown -R abc:abc /root

chmod +x /app/yt-dlp/updater.sh
chmod +x /app/yt-dlp/yt-dlp.sh
chmod +x /config/post-execution.sh
chmod +x /app/scripts/add_mp3_thumbnail.py
chmod +x /app/scripts/album_updater.py
chmod +x /app/scripts/artist_disambiguator.py
chmod +x /app/scripts/artists_folder_capitalize.py
chmod +x /app/scripts/artists_folders_fixer.py
chmod +x /app/scripts/artists_folders_merger.py
chmod +x /app/scripts/artists_invalid_characters_remover.py
chmod +x /app/scripts/artists_tag_fixer.py
chmod +x /app/scripts/capitalize_fixer.py
chmod +x /app/scripts/capitalize_folders_and_tags_accents.py
chmod +x /app/scripts/capitalize_tags_files_and_folders.py
chmod +x /app/scripts/complete_missing_covers.sh
chmod +x /app/scripts/downloads_invalid_characters_remover.py
chmod +x /app/scripts/downloads_mover.py
chmod +x /app/scripts/dz_db_downloader.py
chmod +x /app/scripts/jellyfin_album_downloader.py
chmod +x /app/scripts/jellyfin_artist_downloader.py
chmod +x /app/scripts/lastgenre.py
chmod +x /app/scripts/loudnorm.sh
chmod +x /app/scripts/missing_covers_downloader.py
chmod +x /app/scripts/music_invalid_characters_remover.py
chmod +x /app/scripts/plex_album_downloader.py
chmod +x /app/scripts/plex_artist_downloader.py
chmod +x /app/scripts/release_year_update.py
chmod +x /app/scripts/tags_and_folders_strings_fixer.py
chmod +x /app/scripts/tracks_updater.py
chmod +x /app/scripts/trash_collector.py
chmod +x /app/scripts/unofficial_albums_mover.py
chmod +x /app/scripts/youtube_tracks_folder.py
chmod +x /app/scripts/youtube_tracks_tag.py
chmod +x /app/scripts/unknown_artist_cover.py