#!/usr/bin/with-contenv bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /downloads
chown -R abc:abc /var/run/s6/services
chown -R abc:abc /root

chmod +x /app/youtube-dl/updater.sh
chmod +x /app/youtube-dl/youtube-dl.sh
chmod +x /config/post-execution.sh
chmod +x /app/extended-scripts/logs_cleaner.py
chmod +x /app/extended-scripts/wordnet_corpus_downloader.py
chmod +x /app/extended-scripts/invalid_characters_remover.py
chmod +x /app/extended-scripts/complete_missing_covers.py
chmod +x /app/extended-scripts/complete_missing_covers.sh
chmod +x /app/extended-scripts/trash_collector.py
chmod +x /app/extended-scripts/unofficial_albums_mover.py
chmod +x /app/extended-scripts/loudnorm.sh
chmod +x /app/extended-scripts/capitalize_tags_files_and_folders.py
chmod +x /app/extended-scripts/capitalize_folders_and_tags_accents.py
chmod +x /app/extended-scripts/replace_folders_and_tags_words.py
chmod +x /app/extended-scripts/tags_and_folders_full_strings_fixer.py
chmod +x /app/extended-scripts/add_mp3_thumbnail.py
chmod +x /app/extended-scripts/release_year_update.py